# Generated by Django 2.2.4 on 2019-08-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
