apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: djangoblog
  labels:
    deployment: djangoblog
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: djangoblog
  template:
    metadata:
      labels:
        pod: djangoblog
    spec:
      containers:
        - name: djangoblog
          image: gcr.io/useful-patrol-252015/django
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql
                  key: password

        # [START proxy_container]
        - image: gcr.io/cloudsql-docker/gce-proxy:1.05
          name: cloudsql-proxy
          command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                    "-instances=useful-patrol-252015:europe-west1:polls-instance=tcp:5432",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          volumeMounts:
            - name: cloudsql-oauth-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
            - name: ssl-certs
              mountPath: /etc/ssl/certs
            - name: cloudsql
              mountPath: /cloudsql



#        # [start nginx]
#        - name: nginx
#          image: gcr.io/useful-patrol-252015/nginx
#          ports:
#            - containerPort: 8080
#          command: ["nginx", "start"]
      # [END proxy_container]
      # [START volumes]
      volumes:
        - name: cloudsql-oauth-credentials
          secret:
            secretName: cloudsql-oauth-credentials
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs
        - name: cloudsql
          emptyDir:
      # [END volumes]
