apiVersion: batch/v1
kind: Job
metadata:
  name: djangoblog-collectstatic
spec:
  template:
    spec:
      containers:
        - name: djangoblog
          image: gcr.io/useful-patrol-252015/django
          command: ['python', 'manage.py', 'collectstatic', '--no-input']
          env:
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql
                  key: password

      restartPolicy: Never
  backoffLimit: 5
