kind: Service
apiVersion: v1
metadata:
  name: djangoblog-service
spec:
  selector:
    pod: djangoblog
  ports:
  - protocol: TCP
    port: 80
    # Host service on port 80, get data from port 8000 (djangoblog deployment)
    targetPort: 8000
  type: LoadBalancer
